// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEUGeayCzIjF6e04ZOmVudp2KGLLdhV8',
    appId: '1:30667587127:web:1ee7e9fc2c0d81689dc9b2',
    messagingSenderId: '30667587127',
    projectId: 'social-media-f36b8',
    authDomain: 'social-media-f36b8.firebaseapp.com',
    storageBucket: 'social-media-f36b8.firebasestorage.app',
    measurementId: 'G-508LEBEX43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkFW_80JRR8n5Ynv5CJZ1reowLuRnSls',
    appId: '1:30667587127:android:5a4baffd4bd4af069dc9b2',
    messagingSenderId: '30667587127',
    projectId: 'social-media-f36b8',
    storageBucket: 'social-media-f36b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbJqn8dYmkQox1xkOiFqbBdPc67F0n82Q',
    appId: '1:30667587127:ios:e5adb959aaaa30459dc9b2',
    messagingSenderId: '30667587127',
    projectId: 'social-media-f36b8',
    storageBucket: 'social-media-f36b8.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbJqn8dYmkQox1xkOiFqbBdPc67F0n82Q',
    appId: '1:30667587127:ios:e5adb959aaaa30459dc9b2',
    messagingSenderId: '30667587127',
    projectId: 'social-media-f36b8',
    storageBucket: 'social-media-f36b8.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfEUGeayCzIjF6e04ZOmVudp2KGLLdhV8',
    appId: '1:30667587127:web:ae41c591fec9c5c79dc9b2',
    messagingSenderId: '30667587127',
    projectId: 'social-media-f36b8',
    authDomain: 'social-media-f36b8.firebaseapp.com',
    storageBucket: 'social-media-f36b8.firebasestorage.app',
    measurementId: 'G-B858MFJD0E',
  );
}
